stages:
  - stage: build
    pool:
      vmImage: ubuntu-latest # Default agent pool for Azure Pipelines
    jobs:
      - job: build_docker_images
        steps:
          - bash: docker login -u $(staging.registry) -p "$DOCKER_PASSWORD"
            displayName: Login to docker registry
            env:
              DOCKER_PASSWORD: $(staging.registry.password)
          - bash: |
              echo "##vso[task.setvariable variable=IMAGE_TAG;isOutput=true]$(git rev-parse --short HEAD)"
              echo $IMAGE_TAG
            displayName: Set IMAGE_TAG based on git commit
            name: setImageTag
          - template: ./templates/build-and-push-image.yaml
            parameters:
              image_registry: $(staging.registry)
              image_name: $(client.image.name)
              image_tag: $(setImageTag.IMAGE_TAG)
              dockerfile_path: ../
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: $(artifact.name)
